### PR TITLE
add unit test for GHC 8.10+

### PR DESCRIPTION
**Pull request by tycho01**

### CODE REVIEW

**Comment by gelisam** [comment]
Thanks, but that's not quite what I want to test! This tests that `ifInterpreterNotRunning` is disabled on ghc-8.10, but I am not worried that we'll somehow accidentally reactivate it in the future. What I do want to know is whether disabling `ifInterpreterNotRunning` on ghc-8.10 is a safe thing to do. In order to do that, I want to reproduce the bad things which `ifInterpreterNotRunning` were protecting us from, and then check that those bad things don't occur with ghc-8.10. The result of that investigation may or may not end up being a test, depending on the repro steps. It will definitely involve disabling `ifInterpreterNotRunning` on an older ghc version, and so that part definitely won't be in a test. I tried running a bunch of `interpret "2+2"` in parallel, and it evaluated just fine, so I guess I need to run something more complicated in order to trigger the bad things.

**Comment by gelisam** [comment]
Progress: I ran the entire test suite in parallel, and both instances failed! Well, at first they failed because they were trying to create the same directory and so the second complained that the directory already exists, but I've fixed that and I now get what I hope is a genuine error. Since the error messages are being printed in parallel, it's a bit hard to decipher what's going on though...

```
thread1 started
thread2 started
Cases: 15  Tried: 0  Errors: 0  Failures: 0<interactive>: ^^ Could not load '_TESTzuReloadModified_f_closure', dependency unresolved. See top entry above.

Casces: 15  Tried: 1  Errotrs: 0  Failures: 0ive linking, GHCi couldn't find the following symbol:\n  TESTzuReloadModified_f_closure\nThis may be due to you not asking GHCi to load extra object files,\narchives or DLLs needed by your current session.  Restart GHCi, specifying\nthe missing library using the -L/path/to/object/dir and -lmissinglibname\nflags, or simply by naming the relevant files on the GHCi command line.\nAlternatively, this link failure might indicate a bug in GHCi.\nIf you suspect the latter, please send a bug report to:\n  glasgow-haskell-bugs@haskell.org\n"
### Error in:   0:reload_modified
user error (())
### Failure in: 1:lang_exts F a i l u r e s :   0
/Users/gelisam/working/haskell/hint/unit-tests/run-unit-tests.hs:361
now, it should load
### Failure in: 1:lang_exts
sC.ahsse:s3:6 11orking/haskell/hint/unit-tests/run-unit-test
5n o wT,r iietd :s h3o u lEdr rloorasd:
Cases: 15  Tried: 15  Errors: 0  Failures: 1 Failures: 1
Cases: 15  Tried: 15  Errors: 1  Failures: 1
Cases: 1  Tried: 1  Errors: 0  Failures: 0
 C1a s eEsr:r o1r5s :  T0r i eFda:i l1u r eEsr:r o0r
### Failure in: 1:lang_exts                 0  Failures: 0
/Users/gelisam/working/haskell/hint/unit-tests/run-unit-tests.hs:361
dCw, it should loa
### Failure in: 1:lang_exts                Errsr:o r0s :  F0a i lFuarielsu:r e0s: 1
/Users/gelisam/working/haskell/hint/unit-tests/run-unit-tests.hs:361
now, it should load
aCracshe_sp:a t1h5:se                       urrreosr:s :1 0  Failures: 1
 / UTsreiresd/:g e1l3i s aEmr/rwoorrsk:i n0g / hFaasikleulrle/sh:i n1t/unit-tests/run-unit-tests.hs:361
mod_1 should not be in path (3)
Cases: 15  Tried: 15  Errors: 0  Failures: 1
Cases: 15  Tried: 15  Errors: 0  Failures: 2
Cases: 1  Tried: 1  Errors: 0  Failures: 0
<interactive>: ExitFailure 2
Cases: 1  Tried: 1  Errors: 0  Failures: 0
<interactive>: ExitFailure 4
```

**Comment by gelisam** [comment]
I have deciphered the `now, it should load; ### Failure in: 1:lang_exts` part, and unfortunately that failure is a consequence of my "directory already exists" fix, which merely caused things to break elsewhere.

**Comment by gelisam** [comment]
Having now fixed that mistake, here is the new version of the garbled puzzle:

```
Thread1 started
Thread2 started
Cases: 15  Tried: 2  Errors: 0  Failures: 0<interactive>: ^^ Could not load '_Main_f_closure', dependency unresolved. See top entry above.

GhcException "\nByteCodeLink.lookupCE\nDuring interactive linking, GHCi couldn't find the following symbol:\n  Main_f_closure\nThis may be due to you not asking GHCi to load extra object files,\narchives or DLLs needed by your current session.  Restart GHCi, specifying\nthe missing library using the -L/path/to/object/dir and -lmissinglibname\nflags, or simply by naming the relevant files on the GHCi command line.\nAlternatively, this link failure might indicate a bug in GHCi.\nIf you suspect the latter, please send a bug report to:\n  glasgow-haskell-bugs@haskell.org\n"
 C a s e s :   1 5     T r i e d :   3     E r r o r s :   0     Fe#s#:#  0Error in:   2:work_in_main
user error (())
5C a sTersi:e d1:5  1 3T r iEerdr:o r1s2:   0E r rFoarisl:u r1e s Cases: 15  Tried: 15  Errors: 0  Failures: 0
Cases: 15  Tried: 15  Errors: 1  Failures: 0
Cases: 1  Tried: 1  Errors: 0  Failures: 0
Cases: 1  Tried: 1  Errors: 0  Failures: 00
:C a1s5e s :T r1i5e d :T r2i e dE:r r5o r sE:r r0o r sF:a i0l u rFdC:a s8e s :E r1r5o r sT:r i0e d :F a4i l uErrerso:r s0: 0  FailurCases: 15  Tried: 15  Errors: 0  Failures: 0
Cases: 15  Tried: 15  Errors: 0  Failures: 0
Cases: 1  Tried: 1  Errors: 0  Failures: 0
<interactive>: ExitSuccess
Cases: 1  Tried: 1  Errors: 0  Failures: 0
<interactive>: ExitFailure 1
```

**Comment by tycho01** [comment]
> I tried running a bunch of interpret "2+2" in parallel, and it evaluated just fine

Yeah, I initially just tried to run a few interpreter commands in one test as well, then also had trouble triggering the actual issues.
Glad you managed to actually trigger them now tho!
(I love how it's literally printing two things at once. :joy:)

This sounds pretty subject to race conditions tho... Is the error actually somewhat consistent?
Moreover, does that actually run okay using the new GHC? :sweat_smile:

I tried checking out `review-improvements` branch and running the tests in parallel on old GHC, but somehow they just pass for me -- how did you run them in parallel?
- command: `cabal v1-test --jobs=8`
- `ghc --version`: `8.8.3`

**Comment by gelisam** [comment]
> (I love how it's literally printing two things at once. 😂)

That's a pretty common result when two Haskell threads both print something to the screen at the same time:

```haskell
import Control.Concurrent

-- |
-- >>> main
-- helwloor
-- ld
main :: IO ()
main = do
  _ <- forkIO $ putStrLn "hello"
  _ <- forkIO $ putStrLn "world"
  threadDelay 1000000  -- wait for the threads to finish
```

[The `say` package](http://hackage.haskell.org/package/say) solves that problem:

```haskell
{-# LANGUAGE OverloadedStrings #-}
import Control.Concurrent
import Say

-- |
-- >>> main
-- hello
-- world
main :: IO ()
main = do
  _ <- forkIO $ say "hello"
  _ <- forkIO $ say "world"
  threadDelay 1000000  -- wait for the threads to finish
```

So one of the ways I've been deciphering the garbled output is by temporarily changing `putStrLn`s to `say`s. Unfortunately, some of those `putStrLn`s are in libraries such as `HUnit`, so it would require a bit more effort to change them to `say`. My plan is to minimize the repro case so that it doesn't use `HUnit`.

> This sounds pretty subject to race conditions tho... Is the error actually somewhat consistent?

It seemed pretty consistent to me yesterday, but this morning I am having trouble reproducing it. In particular, `stack test` always succeeds, while `hcid --command="stack repl hint:test:unit-tests" --test=main` seems to fail in a different way every time. I have now noticed that the `Could not load '*_closure', dependency unresolved` error only seems to happen when I save the file while the tests are still running, so I think ghcid kills `main` in a way which doesn't clean up something properly, and so the next instantiation of `main` starts in a weird state.

> Moreover, does that actually run okay using the new GHC? 😅

I haven't tried that yet. I should probably do that before spending all that time minimizing the repro case!

> how did you run them in parallel? [...] `cabal v1-test --jobs=8`

Oh nice, that looks like a much easier way to run the tests in parallel! What I meant is that I tweaked the code to run two copies of `run-unit-tests.hs`'s `main` function in parallel. The resulting code is quite messy and temporary and so I normally wouldn't even commit this, but since you're so eager to help, I have pushed [a branch with my changes for you](https://github.com/haskell-hint/hint/tree/test-multiple-instances). If you want, we could try to do some remote pair programming on this.

I also gave you write access to hint, because hint is in dire need of people who are eager to help ;) But please still use PRs instead of pushing directly to master, so that CI gets the opportunity to run.

**Comment by gelisam** [comment]
>  tried checking out review-improvements branch 

You now have the power to review and merge it if you want ;)

**Comment by tycho01** [comment]
by cabal (no parallel jobs) the branch errors for me with `thread blocked indefinitely in an MVar operation`.
gonna retry with Stack, but interesting that's a different result from yours.

if we can get kinda consistent results, then maybe we could say put the `main1` stuff into a unit test... if calling unit tests from another unit tests is even a thing. :sweat_smile:

**Comment by gelisam** [comment]
>  the branch errors for me with `thread blocked indefinitely in an MVar operation`.

That's good, that means one of the two copies of the test suite failed with an exception, thus causing the thread to die before it can indicate to the main thread that it has completed, by filling in its MVar

**Comment by gelisam** [comment]
...oops, that's actually a bug in my MVar logic, thread 2 should be filling in the `thread2` MVar but instead both threads are filling in `thread1`:

https://github.com/haskell-hint/hint/blob/93a700512b93f21c84946065427a728850328d0d/unit-tests/run-unit-tests.hs#L309

**Comment by gelisam** [comment]
pushed a fix.

**Comment by tycho01** [comment]
cool, thanks! getting it on Stack too fyi so that's good.
lemme try and see if I can test with GHC 8.10 then...

**Comment by tycho01** [comment]
ouch, seems they don't [package](https://www.haskell.org/ghc/download_ghc_8_10_1.html#linux_x86_64) for Arch, which [itself](https://www.archlinux.org/packages/community/x86_64/ghc/) is behind as well.
gonna see if my Nix can get the new one, but so far that also just seems to grab `8.6.5`...

**Comment by gelisam** [comment]
For what it's worth, I used `ghcup` to install `ghc-8.10` on my machine, and to easily switch between ghc versions.

**Comment by tycho01** [comment]
thanks, that was helpful!
I seem to get similar results on 8.10 tho -- that's not quite what we expected here huh...

```
$ stack --system-ghc test
hint> test (suite: unit-tests)

Thread1 started
Cases: 15  Tried: 0  Errors: 0  Failures: 0Thread2 started
Cases: 15  Tried: 0  Errors: 0  Failures: 0unit-tests: thread blocked indefinitely in an MVar operation

hint> Test suite unit-tests failed
Test suite failure for package hint-0.9.0.2
    unit-tests:  exited with: ExitFailure 1
Logs printed to console

$ cabal v2-test --enable-tests
Build profile: -w ghc-8.10.1 -O1
In order, the following will be built (use -v for more details):
 - hint-0.9.0.2 (test:unit-tests) (first run)
Preprocessing test suite 'unit-tests' for hint-0.9.0.2..
Building test suite 'unit-tests' for hint-0.9.0.2..
Running 1 test suites...
Test suite unit-tests: RUNNING...
Cases: 15  Tried: 0  Errors: 0  Failures: 0Thread1 started
Thread2 started
unit-tests: thread blocked indefinitely in an MVar operation
Test suite unit-tests: FAIL
Test suite logged to:
/meltan/downloads/repos/hint/dist-newstyle/build/x86_64-linux/ghc-8.10.1/hint-0.9.0.2/t/unit-tests/test/hint-0.9.0.2-unit-tests.log
0 of 1 test suites (0 of 1 test cases) passed.
cabal: Tests failed for test:unit-tests from hint-0.9.0.2.
```

**Comment by gelisam** [comment]
[Like I said earlier](https://github.com/haskell-hint/hint/pull/93#issuecomment-616153186), the `thread blocked indefinitely in an MVar operation` is not the good news I thought it was. I just saw the `Could not load '*_closure', dependency unresolved` on `ghcid --command="stack repl hint:test:unit-tests" --test=main`'s first run, so I was also wrong about ghcid killing main in a way which doesn't clean up something properly; that's good, I think this means that `stack test`, `ghcid --test=main` and `cabal new-test` simply have slightly different timings, and so it should be possible to reproduce the `*_closure` failure in `stack test` and `cabal new-test` by tweaking the code to force the correct timing!

**Comment by gelisam** [comment]
We're clearly both working on this at the same time, would you like to do some remote pair programming?

**Comment by gelisam** [comment]
I now got a `thread blocked indefinitely in an MVar operation` in `stack test`, despite my fix! That's a good sign!

**Comment by tycho01** [comment]
sorry just returned from a dinner break, let me catch up again. :)

**Comment by gelisam** [comment]
In the version I have just pushed, which shouldn't change anything semantically but obviously seems to change something to the timing, `stack test` seems to _always_ fail, but not always with the same error message.

**Comment by gelisam** [comment]
...but `cabal new-test` always succeeds

**Comment by gelisam** [comment]
oh! it always says `1 of 1 test suites (1 of 1 test cases) passed`, but the _log_ file sometimes contains failures!

**Comment by gelisam** [comment]
...but I see errors even with ghc-8.10, meaning it's probably again a mistake in how the tests are written.

**Comment by gelisam** [comment]
I found one of those mistakes: the `test_signal_handlers` test is replacing the global signal handlers and making sure that hint doesn't overwrite them; but of course, if we run that test twice in parallel, it will look like something else (namely the other test) does overwrite them. I have pushed a change which disables that test (by disabling the IO tests, since that's the only IO test so far)

**Comment by gelisam** [comment]
The `test_work_in_main` test is consistently triggering the `*_closure` message, with both `stack test` and `cabal new-test` (at least when I run enough copies of the test in parallel), but it does _not_ trigger the message when I use ghc-8.10! Hurray! I have pushed changes which focus on that test and bump up the number of threads.

**Comment by tycho01** [comment]
nice! that's great news, glad that the 8.10 branch actually fixes the threading issues! :sparkles: :tada:  :100:

**Comment by tycho01** [comment]
aside from maybe clean up the unused `main2`, what else should still happen here?

**Comment by gelisam** [comment]
I have now used stm to enforce a consistent execution order, so the test is no longer depending on a race condition. All that's left is to clean it up and incorporate it into the test suite!

**Comment by gelisam** [comment]
Hmm, the `test_seach_path` fails for me with ghc-8.10, it passes on your machine?

**Comment by gelisam** [comment]
Well, clearly it passes on CI. So I guess this must be specific to macOS.

**Comment by tycho01** [comment]
rerunning just that one, I'm also seeing errors now:
```
Test suite unit-tests: RUNNING...
unit-tests: ^^ Could not load 'Main_f_closure', dependency unresolved. See top entry above.

Thread1 started
Thread2 started
Thread2 Left (GhcException "\nByteCodeLink.lookupCE\nDuring interactive linking, GHCi couldn't find the following symbol:\n  Main_f_closure\nThis may be due to you not asking GHCi to load extra object files,\narchives or DLLs needed by your current session.  Restart GHCi, specifying\nthe missing library using the -L/path/to/object/dir and -lmissinglibname\nflags, or simply by naming the relevant files on the GHCi command line.\nAlternatively, this link failure might indicate a bug in GHCi.\nIf you suspect the latter, please send a bug report to:\n  glasgow-haskell-bugs@haskell.org\n")
Thread2 done
unit-tests: thread blocked indefinitely in an STM transaction
Test suite unit-tests: FAIL
```

**Comment by gelisam** [comment]
You're getting the `Main_f_closure` failure with ghc-8.10? Oh no :(  
It definitely shouldn't occur in `test_seach_path` though, since there is no `f` involved.

The failure I get for `test_search_path` is more pedestrian, it's `Could not find module "M314719906671811640480952"` (the phantom module).

**Comment by gelisam** [comment]
Ah, it passes on CI because CI isn't using ghc-8.10!

**Comment by gelisam** [comment]
I have opened another issue #97 to track that `test_search_path` issue, let's focus on the `*_closure` failure in this one.

**Comment by gelisam** [comment]
Huh, I'm surprised github let me push to your branch! Let me know if you'd rather I didn't.

**Comment by gelisam** [comment]
All right, I am happy with this new test, will you review and merge?

**Comment by tycho01** [comment]
looks good! it's in the 8.10 branch now. :)

**Pull request merged**
