### PR TITLE
Add support for GHC 9.10

### PR DESCRIPTION
**Pull request by christiaanb**

### CODE REVIEW

**Comment by christiaanb** [comment]
@gelisam I cannot reproduce the failures locally. Can you?

**Comment by gelisam** [comment]
Well, the error is `The package list for 'hackage.haskell.org' does not exist. Run 'cabal update' to download `, so the issue is clearly in the CI script, not in your code.

My CI script has been pretty unreliable, so it might be easier to switch to [the standard CI script](https://github.com/haskell-CI/haskell-ci) than to debug mine.

**Comment by gelisam** [comment]
Thanks for your patience. I still haven't found the time to fix CI, but [I will merge this PR anyway](https://github.com/haskell-hint/hint/pull/176#issuecomment-2308632191).

**Comment by gelisam** [comment]
[released as hackage revision hint-0.9.0.8-r1](https://github.com/haskell-hint/hint/issues/177#issuecomment-2462215510).

**Pull request merged**
